project:
  type: Learning everyday
  output-dir: docs

website:
  title: "bloggy"
  navbar:
    right:
      - text Blog
      - href: blog.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme: cosmo
    css: styles.css



