project:
  type: website
  output-dir: docs

website:
  title: "Learn Every Day"
  navbar:
   right: 
      - text : Blog
        href: blog.qmd
        icon: pen-fill
      - text : Sandrine
        href: About.qmd
      - icon: github
        href: https://github.com/



format:
  html:
    theme:
      - assets/stylesheets/coeos.scss
    code-block-bg: true
    lang: en


