project:
  type: website
  output-dir: docs

website:
  title: "Learn Every Day"
  navbar:
    right:
      - text: Blog
      - href: blog.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme: cosmo
    css: styles.css



